run query check

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -18,24 +18,24 @@ jobs:
     
     - name: Send Query and Check Result
       run: |
-      result=$(curl -X 'POST' \
-        "https://${{ secrets.ENV_HOST}}:8443/qs/systems/local/queries" \
-        -H "Authorization: Basic ${{ secrets.ENV_AUTH }}" \
-        -H "Accept: application/vnd.com.teradata.rest-v1.0+json" \
-        -H "Content-Type: application/json" \
-        -d '{
-              "query": "SELECT count(*) FROM teddy_retailers_ci.new_online_store WHERE transaction_id = 1;",
-              "format": "array",
-              "includeColumns": true
-            }' \
-        --insecure) 
-        
-      count=$(echo $result | jq -r '.results[0].data[0][0]')
-      echo $count
+        result=$(curl -X 'POST' \
+          "https://${{ secrets.ENV_HOST}}:8443/qs/systems/local/queries" \
+          -H "Authorization: Basic ${{ secrets.ENV_AUTH }}" \
+          -H "Accept: application/vnd.com.teradata.rest-v1.0+json" \
+          -H "Content-Type: application/json" \
+          -d '{
+                "query": "SELECT count(*) FROM teddy_retailers_ci.new_online_store WHERE transaction_id = 1;",
+                "format": "array",
+                "includeColumns": true
+              }' \
+          --insecure) 
+          
+        count=$(echo $result | jq -r '.results[0].data[0][0]')
+        echo $count
 
-      if [[ "$count" == "1" ]]; then
-        echo "Test Passed"
-      else
-        echo "Test Failed"
-        exit 1
-      fi
+        if [[ "$count" == "1" ]]; then
+          echo "Test Passed"
+        else
+          echo "Test Failed"
+          exit 1
+        fi
